# Generated by Django 2.2.6 on 2019-10-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('user_address', models.TextField()),
                ('user_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtujedi.Branch')),
                ('user_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtujedi.Sem')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='projects-images/')),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_description', models.TextField()),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtujedi.Branch')),
                ('book_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtujedi.Sem')),
            ],
        ),
    ]
